#!/bin/bash
echo "Create a new repository on GitHub. ...
Open TerminalTerminalGit Bashthe terminal.
Change the current working directory to your local project.
Initialize the local directory as a Git repository. ...
Add the files in your new local repository. ...
Commit the files that you've staged in your local repository." > output.txt
